// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9i2GVpWHzEOglX-klhPef04zO3LVKm_M',
    appId: '1:240529077797:web:be5b27f06a6ec32e0ff1cc',
    messagingSenderId: '240529077797',
    projectId: 'expense-tracker2-ceb17',
    authDomain: 'expense-tracker2-ceb17.firebaseapp.com',
    storageBucket: 'expense-tracker2-ceb17.firebasestorage.app',
    measurementId: 'G-YZR58P5Y8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfX30dXR6CHny9j8TI98gux3_pDGSgR-c',
    appId: '1:240529077797:android:91936270c5c1916e0ff1cc',
    messagingSenderId: '240529077797',
    projectId: 'expense-tracker2-ceb17',
    storageBucket: 'expense-tracker2-ceb17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJRgkYbxY8lhIPj-15-fRD5bf-laRiT-w',
    appId: '1:240529077797:ios:1d6fad0ab660816f0ff1cc',
    messagingSenderId: '240529077797',
    projectId: 'expense-tracker2-ceb17',
    storageBucket: 'expense-tracker2-ceb17.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
